### ISSUE TITLE
User Story #1 List of Birthdays

### ISSUE THREAD

**Issue by AntjeWalter** [AntjeWalter/user-stories#1]
## Value Proposition

**As a** user

**I want to** see a list of my family's and friends' birthdays

**to be able to** remember them early enough to think about presents.

## Description

Scribble / design or text
<img width="334" alt="Bildschirmfoto 2022-12-09 um 14 03 52" src="https://user-images.githubusercontent.com/115352305/206708700-9e8cde25-2990-4388-8b0a-9d27352d0c56.png">

## Acceptance Criteria

- [ ] list is displayed in two columns
- [ ] name and corresponding birthday are in the same row
- [ ] there is a headline

## Tasks

- [ ] new branch: feature/list-of-birthdays
- [ ] project setup
- [ ] Global Styles
- [ ] create dummy names and birthdays -> objects
- [ ] create table
- [ ] insert names in column 1 and birthday in column 2

**Comment by muhammed-basaran** [comment]
finde deine Struktur sauber und definitiv machbar. Habe nichts auszusetzen  😌

**Comment by BrainCodeJockey** [comment]
wie immer tippi toppi 🤓

**Comment by julialoeschel** [comment]
:octocat:  lgtm

sehr schöne Story
