### ISSUE TITLE
User Story #12 Assign Universal Ideas

### ISSUE THREAD

**Issue by AntjeWalter** [AntjeWalter/user-stories#10]
## Value Proposition

**As a** user
**I want to** assign the universal ideas to a person
**to be able to** save ideas for whom I do not have ideas yet.

## Description

![Image](https://user-images.githubusercontent.com/115352305/211382396-fe3bc978-5b5d-488b-991f-3ff366a9b393.png)

## Acceptance Criteria

- [ ] every idea has a dropdown menu to select person from entry names
- [ ] selecting person assigns idea to that person and saves it in person's object

## Tasks

- [ ] new branch: feature/assign-universal-ideas
- [ ] create button for dropdown menu
- [ ] clicking on a person in dropdown assigns idea to person's object

**Comment by julialoeschel** [comment]
hey. good story - again :) 
Did you think about the allocation screen ? Do you need a confirmation button to select the person? 
And also, how does it look like when the person is selected? does the name disapear? 

many small things to think about ;)
