### ISSUE TITLE
User Story #13 Sorting Entries

### ISSUE THREAD

**Issue by AntjeWalter** [AntjeWalter/user-stories#11]
## Value Proposition

**As a** user

**I want to** sort my entries alphabetically or by date

**to be able to** find a specific person or birthday faster.

## Description

![Image](https://user-images.githubusercontent.com/115352305/211385221-f7542ced-eff8-4f1f-848a-10bd1b87c90b.png)

## Acceptance Criteria

- [ ] There is a filter dropdown
- [ ] The filter option has at least to sorting options (alphabetical and date)

## Tasks

- [ ] new branch: feature/sorting-entries
- [ ] add filter dropdown
- [ ] add alphabetical and date-sorting option
- [ ] make list appear in different order depending on the chosen filter

**Comment by Elgin-Schultz** [comment]
Yes, very good idea! Sounds very convincing!
