### ISSUE TITLE
User Story #14 Button for Input

### ISSUE THREAD

**Issue by AntjeWalter** [AntjeWalter/user-stories#13]
## Value Proposition

**As a** user

**I want to** click a button to open the input for a new birthday

**to be able to** have more space on the screen for the birthday list.

## Description

![Image](https://user-images.githubusercontent.com/115352305/211388525-315293b2-a747-49a6-9aea-39fb174d9775.png)

## Acceptance Criteria

- [ ] There is button on the bottom right.
- [ ] Clicking the button makes the input field appear.
- [ ] The input is saved in the list.
- [ ] The input field disappears after submit.

## Tasks

- [ ] new branch: feature/button-for-input
- [ ] add button
- [ ] connect button with input field
- [ ] let input field disappear after submitting info

**Comment by Elgin-Schultz** [comment]
This makes sense to me, adding new persons! But I think the Value Proposition is still the copied one from the last US... just a minor fix. (And I dont know if it is necessary to say where the data is stored?) Looking forward to seeing the feature in your app!

**Comment by AntjeWalter** [comment]
Thanks, you're right, I forgot to update the value proposition. I changed it now.
It is already possible to add new people but I just want to change the input from being there all the time to opening it with a button :) Therefore, the data already has a place to be stored ;)
