### ISSUE TITLE
User Story #15 Back Button on Profile Page

### ISSUE THREAD

**Issue by AntjeWalter** [AntjeWalter/user-stories#14]
## Value Proposition

**As a** user

**I want to** be able to return to the previous page from the profile page

**to be able to** get back to where I came from more easily.

## Description

![Image](https://user-images.githubusercontent.com/115352305/212267788-313c239a-81a2-49f5-b8e4-1cfd1e1f3919.png)

## Acceptance Criteria

- [ ] There is a button on the profile page.
- [ ] The button leads you to the previous page (either calendar or index.js).

## Tasks

- [ ] new branch: feature/back-button
- [ ] add button
- [ ] make button dynamic depending on where the user was before coming to the profile page
- [ ] style button

**Comment by AntjeWalter** [comment]
<StyledBackButton onClick={() => router.back()}>
          <Icon back />
        </StyledBackButton>

**Comment by andy-schwedler** [comment]
Yes! Help us users to navigate more easily 🙌
