### ISSUE TITLE
User Story #16 Database and Login

### ISSUE THREAD

**Issue by AntjeWalter** [AntjeWalter/user-stories#15]
## Value Proposition

**As a** user

**I want to** login to my account

**to be able to** get access to my saved birthdays and ideas.

## Description

- info is saved in database
- login page before entering the app

## Acceptance Criteria

- [ ] There is a database connected where all info is saved.
- [ ] There is a Login to save info for a specific account.

## Tasks

- [ ] new branch: feature/database-and-login
- [ ] connect database
- [ ] save all info from all sites
- [ ] add login for Vercel preview and Github

**Comment by NeeleWaehnke** [comment]
sieht gut aus, ich würde evtl nur für diese Userstory 2 PRs machen(also auch 2 Branches), da ich mir vorstellen kann, dass der Code etwas umfangreicher ausfallen könnte :)
