### ISSUE TITLE
User Story #17 A11y

### ISSUE THREAD

**Issue by AntjeWalter** [AntjeWalter/user-stories#16]
## Value Proposition

**As a** user who needs a screen reader
**I want to** have the most possible accessibility features
**to be able to** understand and use the app properly.

## Description

- good choice of html elements
- aria-labels
- aria-roles
- contrasts

## Acceptance Criteria

- [x] The accessibility test has at least 90%

## Tasks

- [ ] new branch: feature/accessibility
- [x] check for html elements and structure
- [x] add aria-labels and roles
- [ ] check contrasts

**Comment by Elgin-Schultz** [comment]
Good example! I have to do that too!
