### ISSUE TITLE
User Story #20 Testing

### ISSUE THREAD

**Issue by AntjeWalter** [AntjeWalter/user-stories#17]
## Value Proposition

**As a** developer
**I want to** test my code
**to be able to** have a reliable app.

## Description

possible tests:
- test birthday calculation
- test sorting entries
- test assigning ideas
- test forms
- test calendar

## Acceptance Criteria

- [ ] All tests are green.

## Tasks

- [ ] new branch: feature/testing
- [ ] new file for tests
- [ ] write tests for different components and units

**Comment by Elgin-Schultz** [comment]
You are a model beaver! Very examplary!!!
