### ISSUE TITLE
User Story #18 README

### ISSUE THREAD

**Issue by AntjeWalter** [AntjeWalter/user-stories#18]
## Value Proposition

**As a** developer
**I want to** have a descriptive README file
**to be able to** understand and use the app properly.

## Description

- The README now has useful information about the app.

## Acceptance Criteria

- [ ] The README explains the functionality of the app.

## Tasks

- [ ] new branch: feature/readme
- [ ] write introduction to app and explain how it work

**Comment by Elgin-Schultz** [comment]
This is very helpful! I love repos where you get an idea what is all about in the readme.
