### ISSUE TITLE
User Story #19 Code Refactoring

### ISSUE THREAD

**Issue by AntjeWalter** [AntjeWalter/user-stories#19]
## Value Proposition

**As a** developer
**I want to** have a clear code structure
**to be able to** understand the app at a later point in time.

## Description

WHAT DO WE WANT? - A CLEAN CODE! - WHEN DO WE WANT IT? - NOW!!

## Acceptance Criteria

- [ ] The Code looks simple and clean.
- [ ] No error messages.

## Tasks

- [ ] new branch: feature/refactoring
- [ ] find code that repeats itself and make it a component
- [ ] favicon
- [ ] empty state: "There are no ideas saved yet" on universal ideas page, "There are no birthdays saved yet" on index
- [ ] check folder structure and names
- [ ] check imports

**Comment by KirstenSchuhmann** [comment]
Well, the description is on point 😂 😁
