### ISSUE TITLE
User Story #2 List with Present Ideas

### ISSUE THREAD

**Issue by AntjeWalter** [AntjeWalter/user-stories#2]
## Value Proposition

**As a** user

**I want to** see present ideas

**to be able to** have individual presents for people in the list.

## Description

Scribble / design or text
<img width="326" alt="Bildschirmfoto 2022-12-09 um 14 15 14" src="https://user-images.githubusercontent.com/115352305/206710692-dee2bfe0-3e54-485f-8b60-1e74322b2da3.png">

## Acceptance Criteria

- [ ] list is displayed in three columns
- [ ] name, idea and corresponding birthday are in the same row

## Tasks

- [ ] new branch: feature/list-with-ideas
- [ ] extend table by one column
- [ ] create dummy present ideas
- [ ] insert ideas in between name and birthday

**Comment by BrainCodeJockey** [comment]
good structure. i like it. : )

**Comment by marvinRoellecke** [comment]
kept it simple, well done 👍
