### ISSUE TITLE
User Story #3 Input fields

### ISSUE THREAD

**Issue by AntjeWalter** [AntjeWalter/user-stories#3]
## Value Proposition

**As a** user

**I want to** add new people, their birthdays and present ideas

**to be able to** extend the list of birthdays.

## Description

Scribble / design or text
<img width="277" alt="Bildschirmfoto 2022-12-09 um 14 21 26" src="https://user-images.githubusercontent.com/115352305/206711799-843f59ec-78ee-4b70-ba43-54889754bbae.png">

## Acceptance Criteria

- [ ] there are three input fields
- [ ] there is a submit button 
- [ ] the added input is displayed in the correct order

## Tasks

- [ ] new branch: feature/input
- [ ] add three inputs/textareas
- [ ] add submit button
- [ ] make input appear in correct column
