### ISSUE TITLE
User Story #4 Editable infos

### ISSUE THREAD

**Issue by AntjeWalter** [AntjeWalter/user-stories#4]
## Value Proposition

**As a** user
**I want to** be able to change the existing info
**to be able to** correct mistakes in name or birthday and add more present ideas.

## Description

![Image](https://user-images.githubusercontent.com/115352305/207083683-8601d7bb-cd96-4739-8535-6e046ab91f85.png)

- either information can be directly clicked and changed or 
- implement edit-button for changing info

## Acceptance Criteria

- [ ] every information is editable
- [ ] old information stays in field and has to be actively deleted in order to not mistakenly delete info.

## Tasks

- [ ] new branch: feature/editable-infos
- [ ] either install React extension or choose other way to make all info editable
- [ ] implement logic (e.g. edit-button) for whole table
