### ISSUE TITLE
User Story #5 Local Storage

### ISSUE THREAD

**Issue by AntjeWalter** [AntjeWalter/user-stories#5]
## Value Proposition

**As a** user
**I want to** see my latest changes and additions in the app after reloading the app
**to be able to** save my ideas and not forget birthdays.

## Description

- local storage makes changes in the app appear even after reload of the app

## Acceptance Criteria

- [ ] data is stored in local storage so that after reload new data is still available

## Tasks

- [ ] new branch: feature/local-storage
- [ ] implement local storage
