### ISSUE TITLE
User Story #9 Calendar Page

### ISSUE THREAD

**Issue by AntjeWalter** [AntjeWalter/user-stories#6]
## Value Proposition

**As a** user

**I want to** see the current month 

**in order to** have an overview of the upcoming birthdays. 

## Description

![Image](https://user-images.githubusercontent.com/115352305/208460804-8672b74f-901e-41d6-b933-d302fc0f7d92.png)

## Acceptance Criteria

- [ ] second page with calendar which shows the current month
- [ ] birthdays can be added
- [ ] added birthdays are saved in local storage

## Tasks

- [ ] new branch: feature/calendar-page
- [ ] create new page
- [ ] add MUI calendar
- [ ] add navigation bar in footer
- [ ] make sure that birthdays can be added
- [ ] save birthdays in local storage

**Comment by flipkoehler** [comment]
du nutzt MUI?! Ich bin gespannt und neugierig auf den PR :)

**Comment by AntjeWalter** [comment]
I changed the calendar from MUI to react-calendar which you can download via npm.
Also, adding birthdays via the calendar will come in the next US :)
