### ISSUE TITLE
User Story #7 Navigation Bar

### ISSUE THREAD

**Issue by AntjeWalter** [AntjeWalter/user-stories#7]
## Value Proposition

**As a** user
**I need** a navigation bar 
**to be able to** switch between calendar and list of birthdays and ideas.

## Description

Scribble / design or text

## Acceptance Criteria

- [ ] navigation bar with two tabs
- [ ] clicking on the text makes the user switch between pages

## Tasks

- [ ] add navigation bar
- [ ] link the correct pages
