### ISSUE TITLE
User Story #10 Calendar Routes

### ISSUE THREAD

**Issue by AntjeWalter** [AntjeWalter/user-stories#8]
## Value Proposition

**As a** user

**I want to** click on the names below the calendar

**in order to** see the present ideas for the person. 

## Description

![Image](https://user-images.githubusercontent.com/115352305/210972382-dac53a71-3e10-4005-9ead-e9bd95361a26.png)

## Acceptance Criteria

- [ ] Names under calendar can be clicked and redirect you to the profile page

## Tasks

- [ ] new branch: feature/calendar-routes
- [ ] change name display under calendar to list
- [ ] turn names to Links and use dynamic routes to get to profile page
