### ISSUE TITLE
User Story #11 Universal Present Ideas

### ISSUE THREAD

**Issue by AntjeWalter** [AntjeWalter/user-stories#9]
## Value Proposition

**As a** user

**I want to** save universal present ideas

**in order to** have ideas that can be used for birthdays without individual ideas or other occasions like Christmas.

## Description

![Image](https://user-images.githubusercontent.com/115352305/211382260-26dcf864-34ad-434b-8734-7bef42b28817.png)

## Acceptance Criteria

- [ ] There is a third page.
- [ ] This page has an input to save ideas.
- [ ] The ideas are editable and deletable. 

## Tasks

- [ ] new branch: feature/universal-ideas
- [ ] create new page
- [ ] create input field
- [ ] submit/save button
- [ ] make input appear in list
- [ ] make ideas editable and deletable with buttons

**Comment by julialoeschel** [comment]
Hey There, 
good story. 
I am missing the buttons for edit and delete.
Also if the edit screen looks different, a second scribble would be necessary (in a perfect world) 

other that this - looking good!!!
